services:
    # Manages the autocomplete data resolvers declared throughout the application.
    zitec.form_autocomplete.data_resolver_manager:
        class: Zitec\FormAutocompleteBundle\DataResolver\DataResolverManager
        public: true

    # The autocomplete form field type.
    zitec.form_autocomplete.form.type.autocomplete_type:
        class: Zitec\FormAutocompleteBundle\Form\Type\AutocompleteType
        arguments: ['@router', '@zitec.form_autocomplete.data_resolver_manager']
        tags:
            - { name: form.type, alias: zitec_autocomplete }
